// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLStats.Data;

#nullable disable

namespace QLStats.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223163006_AddSeasonStandings")]
    partial class AddSeasonStandings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLStats.Data.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_type");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map");

                    b.Property<string>("MatchGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_guid");

                    b.Property<int>("QLServerId")
                        .HasColumnType("integer")
                        .HasColumnName("ql_server_id");

                    b.Property<string>("ServerTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("server_title");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int?>("TeamBlueRounds")
                        .HasColumnType("integer")
                        .HasColumnName("team_blue_rounds");

                    b.Property<int?>("TeamRedRounds")
                        .HasColumnType("integer")
                        .HasColumnName("team_red_rounds");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("MatchGuid")
                        .IsUnique()
                        .HasDatabaseName("ix_matches_match_guid");

                    b.HasIndex("QLServerId")
                        .HasDatabaseName("ix_matches_ql_server_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_matches_started_at");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer")
                        .HasColumnName("damage_dealt");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("integer")
                        .HasColumnName("damage_taken");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<string>("Medals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("medals");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("RoundsLost")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_lost");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_won");

                    b.Property<int>("Suicides")
                        .HasColumnType("integer")
                        .HasColumnName("suicides");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("team");

                    b.Property<string>("Weapons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weapons");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean")
                        .HasColumnName("won");

                    b.HasKey("Id")
                        .HasName("pk_match_players");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_match_players_player_id");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_players_match_id_player_id");

                    b.ToTable("match_players", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("steam_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("SteamId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_steam_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.QLServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ReconnectIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("reconnect_interval_ms");

                    b.Property<string>("ZmqAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("zmq_address");

                    b.HasKey("Id")
                        .HasName("pk_ql_servers");

                    b.ToTable("ql_servers", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.RoundResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<string>("TeamWon")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("team_won");

                    b.HasKey("Id")
                        .HasName("pk_round_results");

                    b.HasIndex("MatchId", "RoundNumber")
                        .HasDatabaseName("ix_round_results_match_id_round_number");

                    b.ToTable("round_results", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.ScoringRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameTypeFilter")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_type_filter");

                    b.Property<string>("MedalType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("medal_type");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal?>("Threshold")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("threshold");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_scoring_rules");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_scoring_rules_season_id");

                    b.ToTable("scoring_rules", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_one_active")
                        .HasFilter("is_active = true");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.SeasonStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer")
                        .HasColumnName("damage_dealt");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("matches_played");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("RoundsLost")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_lost");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_won");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("SnappedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapped_at");

                    b.Property<decimal>("TotalPoints")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("total_points");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_season_standings");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_season_standings_player_id");

                    b.HasIndex("SeasonId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_season_standings_season_id_player_id");

                    b.ToTable("season_standings", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.ZmqEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<int>("QLServerId")
                        .HasColumnType("integer")
                        .HasColumnName("ql_server_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_json");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_zmq_events");

                    b.HasIndex("Processed")
                        .HasDatabaseName("ix_zmq_events_processed");

                    b.HasIndex("QLServerId")
                        .HasDatabaseName("ix_zmq_events_ql_server_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_zmq_events_received_at");

                    b.ToTable("zmq_events", (string)null);
                });

            modelBuilder.Entity("QLStats.Data.Entities.Match", b =>
                {
                    b.HasOne("QLStats.Data.Entities.QLServer", "QLServer")
                        .WithMany("Matches")
                        .HasForeignKey("QLServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_ql_servers_ql_server_id");

                    b.Navigation("QLServer");
                });

            modelBuilder.Entity("QLStats.Data.Entities.MatchPlayer", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_players_matches_match_id");

                    b.HasOne("QLStats.Data.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_players_players_player_id");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("QLStats.Data.Entities.RoundResult", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Match", "Match")
                        .WithMany("RoundResults")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_results_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("QLStats.Data.Entities.ScoringRule", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Season", "Season")
                        .WithMany("Rules")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_rules_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("QLStats.Data.Entities.SeasonStanding", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_standings_players_player_id");

                    b.HasOne("QLStats.Data.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_standings_seasons_season_id");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("QLStats.Data.Entities.ZmqEvent", b =>
                {
                    b.HasOne("QLStats.Data.Entities.QLServer", "QLServer")
                        .WithMany("ZmqEvents")
                        .HasForeignKey("QLServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_zmq_events_ql_servers_ql_server_id");

                    b.Navigation("QLServer");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Match", b =>
                {
                    b.Navigation("MatchPlayers");

                    b.Navigation("RoundResults");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Player", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("QLStats.Data.Entities.QLServer", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("ZmqEvents");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Season", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
