// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLStats.Data;

#nullable disable

namespace QLStats.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221215954_AddDamageTaken")]
    partial class AddDamageTaken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLStats.Data.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SessionDate");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MatchGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("QLServerId")
                        .HasColumnType("integer");

                    b.Property<string>("ServerTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TeamBlueRounds")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamRedRounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("MatchGuid")
                        .IsUnique();

                    b.HasIndex("QLServerId");

                    b.HasIndex("StartedAt");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("QLStats.Data.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundsLost")
                        .HasColumnType("integer");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("QLStats.Data.Entities.QLServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ReconnectIntervalMs")
                        .HasColumnType("integer");

                    b.Property<string>("ZmqAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("QLServers");
                });

            modelBuilder.Entity("QLStats.Data.Entities.RoundResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TeamWon")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "RoundNumber");

                    b.ToTable("RoundResults");
                });

            modelBuilder.Entity("QLStats.Data.Entities.ScoringRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameTypeFilter")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Threshold")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("ScoringRules");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("QLStats.Data.Entities.ZmqEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<int>("QLServerId")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.HasIndex("QLServerId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("ZmqEvents");
                });

            modelBuilder.Entity("QLStats.Data.Entities.GameSession", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Season", "Season")
                        .WithMany("GameSessions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Season");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Match", b =>
                {
                    b.HasOne("QLStats.Data.Entities.GameSession", "GameSession")
                        .WithMany("Matches")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLStats.Data.Entities.QLServer", "QLServer")
                        .WithMany("Matches")
                        .HasForeignKey("QLServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("QLServer");
                });

            modelBuilder.Entity("QLStats.Data.Entities.MatchPlayer", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLStats.Data.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("QLStats.Data.Entities.RoundResult", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Match", "Match")
                        .WithMany("RoundResults")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("QLStats.Data.Entities.ScoringRule", b =>
                {
                    b.HasOne("QLStats.Data.Entities.Season", "Season")
                        .WithMany("Rules")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("QLStats.Data.Entities.ZmqEvent", b =>
                {
                    b.HasOne("QLStats.Data.Entities.QLServer", "QLServer")
                        .WithMany("ZmqEvents")
                        .HasForeignKey("QLServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QLServer");
                });

            modelBuilder.Entity("QLStats.Data.Entities.GameSession", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Match", b =>
                {
                    b.Navigation("MatchPlayers");

                    b.Navigation("RoundResults");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Player", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("QLStats.Data.Entities.QLServer", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("ZmqEvents");
                });

            modelBuilder.Entity("QLStats.Data.Entities.Season", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
